[metadata]
name = odoo-addon-sale_payment_fee
version = 18.0.1.0.0
author = OCA, Odoo Community Association
author_email = support@odoo-community.org
description = Adds a collection fee line to sale orders based on payment terms
long_description = file: README.rst
long_description_content_type = text/x-rst
url = https://github.com/OCA/sale-workflow
project_urls =
    Source = https://github.com/OCA/sale-workflow/tree/18.0/sale_payment_fee
    Tracker = https://github.com/OCA/sale-workflow/issues
license_expression = AGPL-3.0-only
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)
    Programming Language :: Python :: 3
    Framework :: Odoo
    Framework :: Odoo :: 18.0

[options]
packages = find:
include_package_data = True
zip_safe = False
install_requires =
    odoo>=18.0,<19.0
    odoo-addon-sale>=18.0,<19.0
    odoo-addon-account>=18.0,<19.0

[options.extras_require]
test =
    pytest-odoo

[flake8]
max-line-length = 88
exclude = .git,__pycache__,*.egg-info
